name: qqtranslator_edu
description: A new Flutter project.
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  logging: ^0.11.3+2
  build: ^1.1.3
  build_config: ^0.3.2
  redux_logging: ^0.3.0
  shared_preferences: ^0.4.2
  connectivity: ^0.4.2
  device_info: ^0.2.1
  video_player: ^0.6.4
  path_provider: ^0.5.0+1
  sqflite: ^1.1.1
  sembast: ^1.14.0+2
  intl: ^0.15.7
  mutex: ^1.0.1


dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: ^1.5.1+1
  build_runner: ^1.3.3
flutter:
  uses-material-design: true
  assets:
  - assets/
