name: hello
description: A new Flutter project.

version: 1.0.0+1

#environment:
#  sdk: ">=2.1.0 <3.0.0"

dependencies:
#  flutter_webview_plugin: "^0.1.6"
  objectdb: ^1.0.1
  mutex: ^1.0.1
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  path_provider: ^0.4.1
  cupertino_icons: ^0.1.2
  connectivity: '0.3.0'
  device_info: '0.2.0'
  flutter_gallery_assets:
  flutter_webview_plugin:
    path: 'plugins/flutter_webview_plugin'
  video_player:
    path: 'plugins/video_player'
  gbk2utf8:
#  exportable: "^0.1.0"

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/videos/bee.mp4
    - assets/videos/butterfly.mp4

    ###########################################
    ######## images ###########################
    - assets/images/sound_bg.png


  fonts:
    - family: rokkittFamily
      fonts :
      - asset: assets/fonts/Rokkitt.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
